services:
  app:
    build:
      context: .
      dockerfile: ./internal/handler/app/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    command: [ "postgres",
               #"-e", "POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "logging_collector=on",
               "-c", "log_statement=all" ]
    ports:
      - "5436:5432"
#    volumes:
#      - postgres:/var/lib/postgresql/data
  
#volumes:
#  postgres:
